project_id = "qvmtzfvkhkhkhdpclzua"

[functions.meta-whatsapp-webhook]
verify_jwt = false

[functions.meta-whatsapp-send]
verify_jwt = false

[functions.meta-whatsapp-templates-sync]
verify_jwt = false
